-- Area Manager Site Assessment — authored as a DRAFT, 2026-09-24. APPLIED via
-- the Supabase connector at the operator's instruction. DO NOT RE-RUN: it has
-- no guard and a second run creates a duplicate form with the same slug.
--
--   form_id          53ce96b5-81bc-4058-9426-cfedbd9ae613
--   draft_version_id 0913cb46-e396-48ad-a585-3cadfc21520c
--   slug             am-assessment   audience internal   126 fields
--
-- The schema was not hand-written. `scripts/gen-am-assessment.ts` builds it,
-- checks the things Zod does not (duplicate ids, duplicate keys, key shape,
-- every workflow transition and payload_field reference resolving), then runs
-- BOTH formSchemaSchema and draftFormSchemaSchema over it. Re-running the
-- generator reproduces this exact schema — the field ids are a hash of the key,
-- not random — so a future edit is a diff, not a retype.
--
-- Ported from JotForm 250656455549063 ("Area Manager Site Assessment Form").
--
-- WHY THE X / SLASH DROPDOWNS BECAME RADIOS
--
--   The JotForm's own instruction block defines the marks: "A check Mark in a
--   box represents OK, An X in a box represents Not OK", with a blank meaning
--   NA. So the three states are OK / Not OK / N/A, and the punctuation was only
--   ever a paper-form artifact. 89 <select>s is 178 taps on a phone; 89 inline
--   radio rows is 89. Same payload shape either way (dropdown and radio both
--   store one option value), so every consumer — CSV, PDF, wide table — is
--   unaffected.
--
-- WHY THE RATED ROWS ARE NOT REQUIRED
--
--   The JotForm leaves all 89 optional and ships an explicit NA option. A
--   96-required-question form on a phone is a form people abandon two thirds of
--   the way through, and an abandoned assessment tells you less than a partial
--   one. The five section scores ARE required — they are the summary the CEO
--   sign-off actually reads.
--
-- WHY THE SIXTH SCORE BOX IS GONE
--
--   The JotForm's last box is labelled "Overall Score (Average) **Automatically
--   Calculated" and is a plain textbox somebody types into. This schema has no
--   calculated fields, so the honest options were "a box that can disagree with
--   its own five inputs" or "no box". The five section scores are stored; the
--   average is arithmetic anyone reading them can do.
--
-- WHY EVERY KEY CARRIES ITS SUBSECTION PREFIX
--
--   Six labels repeat across subsections — Tunnel, Detail, Fivestar, Oil
--   Change, Electrical, and Other five times over. Keying on the label alone
--   would have silently dropped one of each pair from the payload, with no
--   error anywhere: the later field just overwrites the earlier one's key. The
--   generator asserts key uniqueness rather than trusting the naming scheme.
--
-- ON THE "AM" LABELS
--
--   Per the Brief 59 convention this repo calls pricing_simple.am_email the
--   Regional Director and rm_email the Regional Manager. This form keeps the
--   JotForm's "AM email" / "RM email" labels, because its audience is the
--   people who call themselves Area Managers and relabelling mid-port would
--   make the form disagree with its own title. The COLUMNS are the canonical
--   ones — am_email and rm_email — so the data lines up with every other
--   surface regardless of what the label says.
--
-- WORKFLOW: submit -> email the signer -> sign off or send back -> email the AM
--
--   Six stages: notify_signer (email, attaches the PDF) -> signoff (approval,
--   static_emails) -> notify_signed_off / notify_returned (email) -> signed_off
--   / returned (outcomes). Sign off requires a typed name; Send back requires a
--   note. The email steps are the point: an approval workflow without them only
--   moves a column, and nobody is told.
--
--   The approver is a static_emails list of ONE address, currently
--   josh.copp@splashcarwashes.com, set so the flow can be exercised end to end
--   before it is handed to whoever signs these off for real. Changing it is the
--   Workflow tab, not SQL.
--
--   notify_signed_off / notify_returned address the AM via
--   {type: payload_field, field_key: am_email} — NOT site_role. The am_email
--   lookup has already resolved to an address by the time the cascade runs, so
--   its payload value IS the email; routing through site_role would make the
--   resolver hunt for a location field this form does not have. That is the
--   exact bug class Brief 131 and Brief 132 closed.
--
-- WHY IT IS A DRAFT AND MUST BE PUBLISHED FROM THE UI
--
--   handlePublish does more than copy the schema: it designates the scope field
--   and stamps forms.scope_location_field_key. Without that column, submissions
--   land with a null location_code and every action item belongs to no site —
--   silently, because nothing errors. Same reason rm-visit shipped as a draft.
--   The site field is keyed `site_number` because handlePublish finds the scope
--   field by that literal key; any other key and it appends its own "Site
--   number" box and the form asks twice.
--
-- Verified after apply against what was STORED, not what was sent: 126 fields,
-- 94 radios (89 rated + 5 scores), 20 headings (5 sections + 15 subsections),
-- 3 lookups all pointing at the site field, 90 action-item eligible (89 rated +
-- Comments), 126 distinct keys, 126 distinct ids, 0 malformed keys, 6 workflow
-- stages, default_stage notify_signer, draft_version_id set, status draft,
-- scope_location_field_key still null (publish sets it).
--
-- NEXT STEP IS THE OPERATOR'S: open /admin/forms/53ce96b5-.../ and Publish.

-- (statement intentionally not repeated — see above, do not re-run)

-- ---------------------------------------------------------------------------
-- Label qualification. APPLIED 2026-09-25 to the DRAFT (v2) via the connector.
--
-- v1 shipped 106 payload fields carrying only 92 distinct labels. A label is
-- not just fill-time text -- it is the column header in the Brief 119
-- submissions table, the row label in the Brief 129 PDF the signer reads, and
-- the column name in the CSV. So the viewer had five columns headed "Other",
-- three headed "Fivestar", and pairs of Tunnel / Detail / Oil Change /
-- Electrical, with no way to tell which was which short of counting columns.
--
-- Nothing was ever LOST -- the keys were distinct from the start -- which is
-- exactly why this would not have surfaced as a bug. It reads as data that is
-- merely hard to follow.
--
-- 21 repeating labels gained their subsection in parentheses ("Other
-- (Visibility)", "Electrical (Hazards)"). Subsection names are unique across
-- this form, so they qualify on their own; the full section path would have
-- bloated every one of them to disambiguate a handful. The 5 score labels also
-- gained the word "score" -- not duplicates, but the same defect: a CSV column
-- headed "Safety" holding a bare 3, among columns of OK / Not OK, does not read
-- as a 1-3 rating to anyone who was not there.
--
-- The generator derives this rather than carrying a list of the 21 offenders,
-- so a row added later that happens to collide is qualified on the next run
-- instead of silently joining the ambiguous set, and it asserts label
-- uniqueness afterwards rather than assuming the pass worked.
--
-- WHY THIS WAS A TARGETED UPDATE AND NOT A SCHEMA REWRITE
--
--   Regenerating proved the change was labels and nothing else: same 126 keys
--   in the same order, same 126 ids, zero non-label differences between the two
--   JSON blobs. So the statement set `label` per key and left the rest of the
--   JSONB alone, which cannot disturb a field it does not name.
--
-- Verified after apply by checksum on BOTH sides, not by reading it back:
-- md5 of the ordered "key=label" list on the stored draft is
-- af44530c78b708410f13d9716d4ee929, byte-identical to the locally generated
-- and Zod-validated schema. md5 of the ordered "key|id|type" list is
-- 81125eca83abdaf6a9ce507516a7caf5 on BOTH v1 and the draft -- structure
-- untouched. Distinct payload labels 92 -> 106, equal to the 106 payload
-- fields, so every column is now unique. Workflow still present.
--
-- The one existing submission is pinned to v1 and renders against v1's schema
-- forever, so it keeps the old labels. That is the versioning working, not a
-- gap.
--
-- NEXT STEP IS THE OPERATOR'S: Publish the draft to make v3 live.
-- ---------------------------------------------------------------------------
