-- UNITS: distances in these comments are MILES and FEET, which is what the
-- operator reads. Stored values stay metric (locations.geofence_radius_m, and
-- the metre arithmetic in the equirectangular distance formula) and are given
-- in parentheses where a comment quotes one, so the prose still ties to the
-- code. The raw data has no units at all -- Geotab supplies degrees.
-- locations-coordinates-04-gps-corrected.sql
--
-- Corrects five site coordinates that were geocoded to the wrong place, using
-- where the mechanics' trucks actually park.
--
-- ===========================================================================
-- HOW THESE WERE FOUND, AND THE CLAIM IT OVERTURNS
-- ===========================================================================
-- On 2026-09-17 the operator asked whether the geofences were too tight, and
-- the answer given was NO: only 3.3% of unattributed paid time sits within
-- 500 ft of a fence and ~90% is over half a mile from one, so the time was
-- called "genuinely elsewhere".
--
-- THAT ANALYSIS MEASURED DISTANCE TO FENCES THAT ARE THEMSELVES MISPLACED. A
-- truck standing in the Blackwood wash is 4.1 miles from Blackwood's recorded
-- coordinates, so it was scored as "over a kilometre from any site" -- it was
-- the very thing the question was trying to detect.
--
-- What survives: widening the RADIUS would not have helped, and still would
-- not. You cannot close a 4.1 mile gap with a bigger circle. The error was in
-- the fence's LOCATION, which no radius check would ever surface.
--
-- THE DETECTOR that generalises, and is worth re-running as sites are added:
-- a site where mechanics punch many hours but GPS almost never places them
-- inside the fence. Four trucks visited Oswego for 85 punched hours and the
-- fence caught SIX MINUTES between them. That is not a mechanic problem.
--
-- ===========================================================================
-- WHY THE NEW CENTRE IS A DWELL CENTROID AND NOT A GEOCODED ADDRESS
-- ===========================================================================
-- Geocoding the street address is what produced the wrong values in the first
-- place (see locations-coordinates-03-geocoded.sql). The centroid of where
-- three or four different trucks actually stop is a direct measurement of the
-- thing the fence is for. Cluster spreads here are 60-415 ft, so the sites are
-- tight and the centroid is well determined.
--
-- Radius set to 656 ft (200 m) on four of the five: it covers Middletown's
-- 415 ft spread with margin, and a wash lot plus its queue is bigger than the
-- 328 ft that three of
-- these carried.
--
-- ===========================================================================
-- IDENTIFICATION IS THE OPERATOR'S, NOT THE ALGORITHM'S -- THIS MATTERS
-- ===========================================================================
-- Candidate clusters were put to the operator and THREE OF THE EIGHT CAME BACK
-- AS RETAIL: a Home Depot, a Lowe's and (initially) McKinley Mall. Multi-truck
-- short-stop clusters are the PARTS-RUN shape, which is the same shape as a
-- warehouse and indistinguishable from a mis-geofenced wash by behaviour
-- alone. Had these been applied on the strength of the pattern, three site
-- geofences would now sit on hardware stores.
--
-- Hamburg is the instructive one. It was REJECTED here as "the mall, not the
-- wash", and the operator then established that the Hamburg wash is an
-- outparcel IN the McKinley Mall lot (3701 McKinley Ave) -- so the cluster was
-- the wash after all. Caution in that direction costs a re-check; the opposite
-- error puts a site's fence on a Best Buy. Never apply one of these without a
-- human naming the place.
--
-- SINGLE-TRUCK CLUSTERS ARE NEVER CANDIDATES, however concentrated the job
-- claim. A mechanic who always punches one site and parks at home produces a
-- cluster that is 100% that job, 43 miles away; proposing it would move a site's
-- geofence onto somebody's house. Two or more trucks is the floor, and the
-- privacy rule in mt-offsite-locations-01.sql applies here too.
--
-- ===========================================================================
-- APPLYING THIS CHANGES NOTHING UNTIL THE TRACKER IS REBUILT
-- ===========================================================================
-- Site matching happens in build_dwell.py against the sites.csv dump, so
-- existing mt_gps_dwell rows keep their old within_geofence flags until
-- refresh.ps1 re-runs. Run it straight after applying.
--
-- Nothing else in the monorepo reads locations.latitude/longitude -- no worker
-- and no page -- so the blast radius is the maintenance tracker alone.
--
-- Expect site costs at these five to RISE and Unattributed to fall. Those
-- hours were always site time; they were being filed as unexplained.

-- Previous values, for reversal:
--   57  Middletown  41.462128, -74.408341  r=328 ft  (2.9 miles from truth)
--   86  Newburgh    41.517857, -74.062170  r=328 ft  (0.75 miles)
--  147  Oswego      43.460966, -76.484950  r=820 ft  (1,110 ft)
--  149  Hamburg     42.789696, -78.811012  r=820 ft  (2,040 ft)
--  231  Blackwood   39.807706, -75.034880  r=328 ft  (4.1 miles)

update public.locations set latitude = 41.422231, longitude = -74.427798, geofence_radius_m = 200 where site_number = 57;
update public.locations set latitude = 41.508030, longitude = -74.068348, geofence_radius_m = 200 where site_number = 86;
update public.locations set latitude = 43.462233, longitude = -76.481010, geofence_radius_m = 200 where site_number = 147;
-- Hamburg gets 394 ft (120 m), not 656. The wash is an outparcel INSIDE the McKinley
-- Mall lot, and the centre here is where the trucks park rather than the
-- wash's street address. A 656 ft circle there would also enclose Best Buy,
-- Firestone and Old Navy, so a parts stop at Best Buy would be credited as
-- on-site time at Hamburg -- the same false positive this file exists to
-- remove, relocated. The cluster spread is 108 ft, so 394 ft is ample.
-- ANY future site in a shared retail lot needs the same treatment: a fence
-- sized to the wash, not to the parking lot it sits in.
update public.locations set latitude = 42.784091, longitude = -78.810574, geofence_radius_m = 120 where site_number = 149;
update public.locations set latitude = 39.748611, longitude = -75.046039, geofence_radius_m = 200 where site_number = 231;

-- ===========================================================================
-- MEASURED AFTER APPLYING AND RE-RUNNING refresh.ps1, 2026-09-17
-- ===========================================================================
-- Share of punched hours the fence now catches, for the three that caught
-- nothing at all before:
--
--   Oswego 147     0%  ->  19%     0.1 h ->  16.4 h
--   Blackwood 231  0%  ->  32%     0.0 h ->  16.6 h
--   Hamburg 149    0%  ->  19%     0.0 h ->   6.7 h
--
-- Site hours now recorded at all five (operating + capital):
--   57 Middletown 17.8 + 6.3    86 Newburgh 18.2    147 Oswego 23.7
--  149 Hamburg    13.7         231 Blackwood 10.1 + 12.5
--
-- Cost centres, before -> after:
--   Sites        1,777 -> 1,879
--   Unattributed   776 ->   715
--   Management   1,512 -> 1,491
--   CapX           423 ->   445
-- (totals also absorb a day of new punches from the same refresh)
--
-- About 100 h moved out of Unattributed into the sites where it was earned.
-- Note it does NOT all land on site: these five are still at 19-32% seen,
-- because a punched hour legitimately includes travel and stops. The fence
-- being right is a precondition for the question, not the answer to it.
--
-- Middletown and Newburgh have no job mapping to their own site numbers --
-- mechanics there punch the "Montgomery" job (74% and 100% of those clusters).
-- Their GPS hours now land correctly, but per-site cost in the Hudson Valley
-- stays unreliable until the punching convention or the job list is fixed.
-- That is a separate problem from the coordinates and is not fixed here.
