-- mt-connecteam-job-site-01.sql
--
-- Recovers the Connecteam jobId -> Splash site crosswalk WITHOUT API access.
--
-- WHY THIS EXISTS
--   Phase 3b (PLAN.md 8) allocates each punch's cost to a site. Nothing in the
--   warehouse records which site a punch is billed to: connecteam_shifts.site_id
--   is the constant 'splash' (a tenant tag), connecteam_timesheets has no site
--   column, and the only site-bearing field is raw_json.jobId -- a UUID, with no
--   jobs table in Redshift to resolve it. The operator confirmed the naming
--   convention (a job is generally a site name; a sub-job is "site name +
--   project") but has lost the API access that would list them. So the mapping
--   is recovered from behaviour instead.
--
-- THE METHOD, AND THE ONE THAT DID NOT WORK
--   FIRST ATTEMPT, DISCARDED: nearest site to the PUNCH-OUT coordinate, on the
--   PLAN.md 8 reading that a mechanic "punches out of that location" when the
--   work is done. It gives 41% modal agreement on the busiest job and 0-1
--   punches inside a fence on the top three. A punch-out happens wherever the
--   mechanic chained one punch into the next -- roadside, at home, mid-drive --
--   not at the site whose work just finished. Only ~20% of punch-outs are
--   inside any fence at all.
--
--   WHAT WORKS: where the VEHICLE SAT during the shift. Per shift, the site
--   whose fence holds the longest residence; per job, the modal site across
--   shifts. Same jobs, same window: 100 / 96 / 94 / 93% modal agreement.
--
--   Residence is the SPAN between first and last ping inside the fence, never
--   the ping COUNT. Geotab goes quiet while parked (Layer B header: 25,491 of
--   25,534 gaps over 5 minutes involve under 100 m of movement), so a 3-hour
--   stay can be two pings while a drive-past at 5-second intervals is dozens.
--   Counting pings ranks the drive-past first. This is the same trap the dwell
--   sessionisation hit from the other direction.
--
-- CORROBORATION THE METHOD WAS NOT FITTED TO
--   Restricted to CONFIDENT+LIKELY, 45 jobs map to 41 distinct sites, and the
--   four sites reached by more than one job are reached by EXACTLY two. That is
--   the "site" + "site project" sub-job pattern the operator described, and
--   nothing in the derivation was told to look for it or could have produced it
--   by construction -- a noise-fitting method would scatter 1,3,5 across sites.
--
-- CIRCULARITY -- READ BEFORE USING THIS FOR COMPLIANCE
--   This crosswalk is derived FROM GPS. "Did the mechanic's GPS match the job's
--   site?" is therefore NOT an independent test of a billing claim: the shift
--   under test helped decide what the job's site is. For per-shift checks,
--   recompute the modal site EXCLUDING that shift (leave-one-out). With 28
--   shifts on the busiest job the difference is small; with 3 it is the whole
--   answer.
--
-- COVERAGE IS PART OF THE OUTPUT, NOT A FOOTNOTE
--   CONFIDENT      41 jobs  503 shifts  (65%)   >=5 shifts, >=80% modal
--   LIKELY          4 jobs   12 shifts  ( 2%)   3-4 shifts, >=80% modal
--   WEAK           13 jobs  125 shifts  (16%)   >=5 shifts, 60-79% modal
--   TOO_FEW_SHIFTS 38 jobs   56 shifts  ( 7%)   1-2 shifts
--   INCONSISTENT   10 jobs   75 shifts  (10%)   spread across sites
--   Only CONFIDENT and LIKELY are fit for cost attribution. The rest are stored
--   rather than dropped so the gap is visible: a crosswalk that silently omits
--   a third of shifts will be read as complete.
--
--   Jobs never worked by one of the 13 crew vehicles cannot appear at all --
--   150 jobIds exist on shifts, 106 are seen here. Absence is absence of GPS,
--   not evidence the job is not a site.
--
-- REFRESH: re-run apps/maintenance-tracker/queries/30_job_site.sql (READ-ONLY,
-- Redshift) and re-apply the insert. Confidence rises as shifts accumulate.

create table if not exists public.mt_connecteam_job_site (
  job_id          text primary key,
  site_number     integer not null,
  confidence      text not null check (confidence in
                    ('CONFIDENT','LIKELY','WEAK','TOO_FEW_SHIFTS','INCONSISTENT')),
  shifts_observed integer not null,
  modal_pct       integer not null,
  distinct_sites  integer not null,
  derived_at      timestamptz not null default now()
);
alter table public.mt_connecteam_job_site enable row level security;

-- Row data is generated; see queries/30_job_site.sql and the insert applied
-- 2026-09-17 (106 rows). Not reproduced here -- it is derived, not source.

-- ===========================================================================
-- THE OVERHEAD ("travel home at end of day") JOB -- LOOKED FOR, NOT FOUND IN USE
-- ===========================================================================
-- The operator states there is an overhead job for the drive home, punched on
-- leaving the last site of the day. Three tests were run to find it, and the
-- answer matters for PLAN.md 8's overhead-travel bucket.
--
--   1. Jobs whose vehicle never enters any fence. Only two qualify, at 12 and
--      7 crew shifts. Far too small to be a company-wide end-of-day habit
--      (13 mechanics x ~45 working days would be hundreds).
--
--   2. Jobs that are the last punch of the day. FIRST ATTEMPT WAS CONFOUNDED
--      and is recorded so it is not repeated: several jobs score 95-100%
--      last-of-day, but their avg_punches_that_day is 1 -- on a single-punch
--      day "last" is also "first" and the test is a tautology. Restricted to
--      days with 2+ punches the field flattens to a 56% maximum and NO job
--      stands out as an end-of-day job.
--
--   3. So where does the drive home live? Crew shifts, multi-punch days:
--
--        earlier punches        565 punches   43% end inside a fence   174 min
--        LAST punch of the day  284 punches    4% end inside a fence   250 min
--
--      The last punch of the day almost never ends at a Splash site, and runs
--      ~76 minutes longer than the others -- about a commute.
--
-- CONCLUSION: the overhead job is a convention that is not being punched. The
-- drive home is absorbed into the TAIL OF THE LAST SITE PUNCH, so it is
-- currently billed to that site rather than to overhead.
--
-- This does not block PLAN.md 8 -- it is the reason 8 defines the buckets by
-- where a leg TERMINATES rather than by what the punch claims. Overhead travel
-- is recoverable from GPS alone: the trailing movement of a punch that ends
-- outside every fence. It also predicts the bucket will be substantial, since
-- 96% of last punches qualify, and 8 already says so: "thirteen mechanics each
-- ending a day somewhere that is not a car wash is thirteen legs a day".
--
-- WHAT NOT TO DO WITH THIS. It is a finding about a punching convention, not
-- about any mechanic. Nobody is over-billing a site on purpose by failing to
-- switch jobs at the end of the day, and the sites' current charges reflect
-- the convention as practised. Moving that time to overhead changes what each
-- site is charged, so it is a decision for the operator, not a correction the
-- tracker should apply silently.


-- ===========================================================================
-- 2026-09-17, LATER: THE API LIST CAME BACK, AND THE DERIVATION WAS TESTED
-- ===========================================================================
-- The operator produced a page of the Connecteam jobs API (200 of ~N jobs,
-- alphabetical, "3" through "Eric Hartnagle"). It changes two things: the
-- crosswalk can be checked against ground truth, and parts of it can be
-- replaced by it.
--
-- A JOB CARRIES ITS SITE NUMBER IN `code` -- on SOME jobs. The field this
-- header says does not exist does exist, unpopulated more often than not:
-- 17 of ~200 jobs on that page have it. Where present it is authoritative
-- ("Auburn" code 159). Where absent -- "Binghamton", "Cicero", "Chili",
-- "Cortland" all have code "" -- the title still names the site, so a
-- title-to-site match covers far more jobs than `code` alone.
--
-- THE TEST. 17 coded jobs; 13 are in this crosswalk. Derived site vs `code`:
--
--   tier             jobs  correct
--   CONFIDENT           4      4     Auburn 159, Batavia II 157,
--                                    Bedford 19, Derby-089 89
--   WEAK                2      2     Commack-186, E.Northport-187
--   TOO_FEW_SHIFTS      6      3     the 3 CapX jobs right; Blackwood-231
--                                    (->75), Cherry Hill-232 (->233),
--                                    Derby CapX (->60) wrong
--   INCONSISTENT        1      0     Brighton-155 CapX (->150)
--
-- 9 of 13 overall, and the distribution is the point: EVERY CONFIDENT row is
-- right, and EVERY error sits in a tier this header already refuses to use for
-- cost attribution. The grading works. The four wrong answers are all 1-3
-- shift jobs where the mechanic also called at a neighbour -- Cherry Hill-232
-- resolved to 233, one site away.
--
-- This is a genuine out-of-sample test: `code` played no part in the
-- derivation and was not known to exist when the tiers were set.
--
-- THE BLIND SPOT THE TITLES EXPOSE, WHICH THE TEST COULD NOT
--   The method takes the modal site of vehicle residence, so it ALWAYS returns
--   a site. It has no way to answer "this job is not a site at all", and the
--   list is full of jobs that are not sites -- CRD, 101 Management, CC
--   Management, Damage Claim, Breaks, Day Off.
--
--   Measured: "CC Management" (79 shifts) is mapped to site 122, and
--   "CC-Management" (14 shifts) to site 221. Both are overhead jobs and
--   neither is a site.
--
--   No cost is wrong today, because both landed in INCONSISTENT and
--   TOO_FEW_SHIFTS and are excluded -- INCONSISTENT is what a job with no real
--   site looks like from behaviour, which is the method half-working. But it
--   is luck, not design: an overhead job whose holder happens to sit at one
--   depot would grade CONFIDENT and be billed to that site with nothing to
--   catch it. A title list removes the whole class by naming which jobs are
--   sites instead of inferring it.
--
-- THE LARGEST JOB IN THE DATA IS UNRESOLVED. "CRD" (d26038b7) carries 354
-- shifts -- more than any other job, and 13% of all 2,731 -- with no `code`,
-- no GPS, and no crosswalk entry. 45 of the 151 jobs seen on shifts are
-- likewise unresolved, together 995 shifts (36%). Whatever CRD is, it is the
-- single biggest thing this tracker cannot currently attribute.
--
-- WHAT THE REST OF THE LIST IS WORTH. Pull the remaining pages and the
-- resolution order becomes: `code` where present (authoritative) -> title
-- matched to mt_site_name -> job GPS (some jobs carry lat/lon and a
-- fenceSize) -> this behavioural crosswalk as the fallback for jobs that
-- have none of the three. That inverts the current arrangement, where
-- inference is the only source.
