-- RM Visit Form — authored as a DRAFT, 2026-09-23. APPLIED via the Supabase
-- connector at the operator's instruction. DO NOT RE-RUN: it has no guard and
-- a second run creates a duplicate form with the same slug.
--
--   form_id          e4bfa6e2-cd4f-4596-8c82-30ea7df2711a
--   draft_version_id a5707cae-54e1-4705-8be4-4ccaa9b43060
--   slug             rm-visit        audience internal        66 fields
--
-- Ported from JotForm 251016031343036 ("RM Visit Form", 73 fields). Dropped:
-- the correction block (fields 58-70) — five fixed "Correction Item and Plan N"
-- + follow-up-date pairs, a manual reminder date and a count-of-items dropdown.
-- That block IS action_items, capped at five and typed by hand, so porting it
-- would have shipped the thing this feature replaces. Also dropped the
-- duplicate second RM Email field.
--
-- WHY IT IS A DRAFT AND MUST BE PUBLISHED FROM THE UI
--
--   handlePublish does more than copy the schema: it designates the scope
--   field and stamps forms.scope_location_field_key. Without that column,
--   submissions land with a null location_code, and every action item belongs
--   to no site — silently, because nothing errors.
--
-- WHY THE SITE FIELD IS KEYED `site_number` BUT TYPED `location`
--
--   handlePublish finds the scope field by KEY (SCOPE_FIELD_KEY ===
--   'site_number'). Any other key and it appends its OWN short-text "Site
--   number" box, so the form would ask for the site twice. Type `location`
--   makes the payload value a canonical location_code already, which is what
--   resolveSubmissionLocationCode wants and what action_items.location_code
--   is copied from.
--
-- A NOTE ON DATA-MODIFYING CTEs, learned the hard way here: the first attempt
-- did INSERT forms / INSERT form_versions / UPDATE forms in one statement. The
-- UPDATE matched nothing, because a statement's CTEs see the snapshot from
-- before it ran — the freshly inserted forms row was invisible to the UPDATE.
-- Both inserts landed and draft_version_id stayed NULL, which is exactly the
-- orphan state Brief 94 documents. Fixed with a separate UPDATE.
--
-- Verified after apply, against what was actually STORED rather than what was
-- sent: 66 fields, 49 radios (47 Pass/Fail/NA + 2 Yes/No), 8 headings, 48
-- action-item eligible, 66 distinct keys, 0 malformed keys, 0 lookups pointing
-- anywhere but the site field, and the two "Glass Cleanliness" rows (Walk-
-- Through and Store) carrying distinct keys. The identical structure was
-- strict-validated against formSchemaSchema locally before insert.
--
-- NEXT STEP IS THE OPERATOR'S: open /admin/forms/e4bfa6e2-.../ and Publish.

-- (statement intentionally not repeated — see above, do not re-run)

-- ---------------------------------------------------------------------------
-- Safety section. APPLIED 2026-09-24 to the DRAFT (v5) via the connector.
--
-- The ported form had three safety-named rows scattered across other sections
-- ("Following Safety Procedure" under Top Wash Package, "PPE Available / In
-- Use" under Walk-Through, "Safety of All Areas" under Customer Self Service)
-- and no Safety heading. That was faithful to the JotForm, but it meant one
-- Pass/Fail stood in for a whole category, and things like the eyewash, the
-- SDS binder and the evacuation plan had nowhere to land except free text.
--
-- Placed SECOND, right after Initial Observations: early on purpose, because
-- it is the section least suited to being reached tired. Not conditional --
-- it applies at every site.
--
-- TWO CHECKBOX GROUPS, NOT ROWS OF PASS/FAIL. For the cabinet and the peroxide
-- gear, what is NOT ticked is the finding. Nine separate Pass/Fail rows would
-- say the same thing in nine times the taps.
--
-- THE PEROXIDE "N/A" IS A GATE, NOT A CHECKBOX. An N/A box sitting alongside
-- the gear boxes can be ticked together with them, and then the row asserts
-- nothing. A Yes/No question gating the group is unambiguous, and reuses the
-- visible_if mechanism the Store and Exit Pad sections already use.
--
-- Strict-validated against formSchemaSchema locally BEFORE insert, including
-- the visible_if reference. The first generator run derived field ids by
-- truncating the key, which collided -- safety_eye_wash and
-- safety_evacuation_plan both start "safety_e" -- and would have put two
-- fields on one DOM id, crossing their <label for=>. Zod does not check id
-- uniqueness; the generator now hashes the key and asserts uniqueness itself.
--
-- Verified after apply: 74 fields, 9 sections in the intended order, 74
-- distinct ids and 74 distinct keys.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- Duplicate label. APPLIED 2026-09-25 to the DRAFT (v8) via the connector.
--
-- v7 had 69 payload fields carrying 68 distinct labels: walkthrough_glass_
-- cleanliness and store_glass_cleanliness were both labelled "Glass
-- Cleanliness". The keys were distinct from the start -- the original port note
-- above even calls them out -- so no data was ever lost or crossed. What was
-- wrong is everything downstream that shows a LABEL rather than a key: two
-- identical columns in the Brief 119 submissions table, two identical rows in
-- the Brief 129 PDF, two identical CSV headers. Nothing errors, so nothing
-- reports it; the reader just cannot tell which is the tunnel glass and which
-- is the store glass.
--
-- Qualified with the enclosing section, matching what am-assessment does:
--   walkthrough_glass_cleanliness -> "Glass Cleanliness (Walk-Through)"
--   store_glass_cleanliness       -> "Glass Cleanliness (Store)"
-- rm-visit has only h3 headings, so the section IS the nearest enclosing
-- heading; on am-assessment, which nests h4s, the qualifier is the subsection.
-- Same rule either way: qualify with the heading directly above.
--
-- The statement was guarded twice rather than trusting the version id: it
-- matched `is_draft = true` so it could not reach a published version, and it
-- only rewrote a label still reading exactly "Glass Cleanliness" so it could
-- not clobber a rename made in the builder in the meantime.
--
-- The two other glass fields ("Glass Cleaner Spray Pattern", "Glass") were
-- already distinct and untouched.
--
-- Verified after apply: draft v8 has 69 distinct payload labels across 69
-- payload fields, and md5 of the ordered "key|id|type" list is
-- 5d5c4ff1bf883fc6d6dd706a67e60aa7 on BOTH v7 and the draft -- structure
-- untouched, labels the only difference. v7 still reads 68, confirming the
-- published version was not reached.
--
-- Submissions already filed against v7 render against v7's schema forever, so
-- they keep the ambiguous pair. That is the versioning working as designed.
--
-- NEXT STEP IS THE OPERATOR'S: Publish the draft to make v8 live.
-- ---------------------------------------------------------------------------
