-- New site onboarding -- stop the form refusing the sites it exists to create.
--
-- Status: APPLIED to the live project (rewokyofschtvqgxrxwl) on 2026-10-01.
--
-- THE BUG. The site-number field was keyed `site_number`, and that key is
-- magic. handlePublish designates a field with it as the form's LOCATION SCOPE
-- (admin/forms.ts, "auto-inject / designate the site-number field"), and the
-- submit path then hard-rejects 422 unknown_site for any value that is not
-- already a known location. Correct for every other internal or link-only form
-- -- one reused across sites must land on a real location_code or it leaks --
-- and exactly inverted here, where the whole point is a site that does not
-- exist yet. The first publish turned it on and the form refused its own first
-- test submission: 'Site number "096" is not a recognized location.'
--
-- TWO CHANGES, and both are needed.
--
--   1. The field is renamed site_number -> new_site_number, so nothing can
--      designate it again.
--
--   2. scope_location_field_key is set to the sentinel '__unscoped__' rather
--      than NULL. resolveSubmissionLocationCode returns `no_scope` when the key
--      names no field in the schema (db/forms.ts line ~520), which is what we
--      want -- but NULL is not safe here: the designation in handlePublish runs
--      only when the column IS null, so a NULL would make the next publish
--      either re-designate a site field or INJECT one, reintroducing the bug.
--
--      A leading underscore cannot be a field key (keys match ^[a-z][a-z0-9_]*$),
--      so the sentinel can never accidentally match a real field. It is spelled
--      to be read: a dangling pointer at an old key would behave identically and
--      look like an oversight.
--
-- Submissions therefore carry location_code NULL and are visible to
-- super_admin / dc-admin, which is right: the approver is a super_admin and the
-- site has no location to scope to until he creates it.
--
-- Generated by scripts/gen-site-onboarding.ts. SAFE TO RE-RUN.
-- REQUIRES A REPUBLISH in the builder to reach the live version.

update public.form_versions v
   set schema = '{"fields":[{"key":"sec_site","id":"928de58f","type":"heading","label":"The site","text":"The site","level":"h3","required":false},{"key":"location_name","id":"33f724ca","type":"short_text","label":"Location name","required":true,"maxLength":200,"helpText":"How the site is referred to in conversation, e.g. Binghamton. Not the web address."},{"key":"new_site_number","id":"764446df","type":"short_text","label":"Site number","required":true,"maxLength":3,"helpText":"Three digits, zero-padded. 069, not 69."},{"key":"street_address","id":"3e4389d4","type":"long_text","label":"Street address","required":true,"maxLength":300,"helpText":"Full postal address, as it should appear on paperwork."},{"key":"site_email","id":"1a5c22f2","type":"email","label":"Site email","required":true,"helpText":"The address the site itself reads. Customer replies and site copies go here."},{"key":"sec_people","id":"6d667d09","type":"heading","label":"Who runs it","text":"Who runs it","level":"h3","required":false},{"key":"rm_name","id":"399d6967","type":"short_text","label":"Regional Manager name","required":true,"maxLength":200},{"key":"rm_email","id":"d9c2bb58","type":"email","label":"Regional Manager email","required":true,"helpText":"This is what grants them access to the site. A name alone does not."},{"key":"am_name","id":"a000c59c","type":"short_text","label":"Regional Director / Area Manager name","required":true,"maxLength":200},{"key":"am_email","id":"6f344263","type":"email","label":"Regional Director / Area Manager email","required":true,"helpText":"Same again: the address is what grants access."},{"key":"sec_packages","id":"324baaf0","type":"heading","label":"Packages","text":"Packages","level":"h3","required":false},{"key":"site_type","id":"f0ef9088","type":"radio","label":"Site type","required":true,"layout":"inline","options":[{"label":"Exterior only","value":"exterior"},{"label":"Full service","value":"full_service"},{"label":"Both","value":"both"}]},{"key":"packages","id":"01105d6b","type":"long_text","label":"Unlimited packages offered","required":true,"maxLength":2000,"helpText":"One package per line, in the form:  name | single wash price | monthly unlimited price. Example:  Bubble Bath | 25.00 | 49.00. Only packages that offer an unlimited plan."},{"key":"notes","id":"0fd39150","type":"long_text","label":"Anything else we should know","required":false,"maxLength":2000,"helpText":"Opening date, pricing that differs from the rest of the region, anything unusual."}],"workflow":{"default_stage":"review","stages":[{"id":"review","label":"Pricing setup","kind":"approval","approver_source":{"type":"static_emails","emails":["josh.copp@splashcarwashes.com"]},"transitions":[{"to":"entered","label":"Entered in pricing","requires":{"typed_name":true}},{"to":"needs_info","label":"Need more detail","requires":{"note":true}}]},{"id":"entered","label":"Entered in pricing","kind":"outcome","tint":"success","transitions":[]},{"id":"needs_info","label":"Need more detail","kind":"outcome","tint":"warning","transitions":[]}]}}'::jsonb
  from public.forms f
 where f.slug = 'site-onboarding' and v.id = f.draft_version_id;

update public.forms
   set scope_location_field_key = '__unscoped__', last_edited_at = now()
 where slug = 'site-onboarding';

select f.slug, f.scope_location_field_key,
       jsonb_array_length(v.schema->'fields') as draft_fields,
       (v.schema->'fields') @> '[{"key":"new_site_number"}]'::jsonb as renamed,
       not ((v.schema->'fields') @> '[{"key":"site_number"}]'::jsonb) as magic_key_gone
  from public.forms f
  join public.form_versions v on v.id = f.draft_version_id
 where f.slug = 'site-onboarding';
