-- Add incident_date to claims.
--
-- The date AND time the customer says the damage actually occurred, which can
-- differ from submitted_at (when the claim form was filled out). A customer
-- may come in days or weeks after an alleged incident; reviewing a claim is
-- hard if the only date on file is the form-submission timestamp.
--
-- Plain TEXT column, nullable, no default, no CHECK — mirroring the
-- vehicle_condition migration. NOTE: nullable at the DB level so this migration
-- stays additive and so legacy/backfill rows (which may only have a calendar
-- date, or none) are accepted — but for NEW claim-form submissions the field is
-- REQUIRED and validated server-side (see the incidentDate gate in
-- src/index.ts). Additive and backwards-compatible: apply before or after the
-- code deploy; the writeClaimBatch legacy fallback tolerates the column being
-- briefly absent during the deploy window.
--
-- Stored as 'YYYY-MM-DD HH:MM[:SS]' — the value an <input type="datetime-local">
-- posts, with the 'T' rewritten to a space so SQLite datetime()/julianday()
-- parse it and it sorts lexically alongside submitted_at. Legacy backfill rows
-- (cicero-backfill.sql) hold date-only 'YYYY-MM-DD' values because no time is
-- known for those historic claims — valid TEXT, read as midnight by SQLite.
--
-- Run (from apps/damage-worker):
--   wrangler d1 execute splash-damage-claims --remote --file=migration-incident-date.sql
ALTER TABLE claims ADD COLUMN incident_date TEXT;
