#!/usr/bin/env python3
"""
Build mt_gps_dwell rows from the Redshift dwell export.

    python build_dwell.py dwell_raw.csv sites.csv > mt_gps_dwell.sql

Takes the stay intervals from queries/20_dwell.sql and attaches the nearest
Splash site to each, using the same per-site geofence radius Layer A uses.

WHY THE SITE MATCH HAPPENS HERE AND NOT IN THE SQL

  The site centres live in Supabase and the pings live in Redshift, and we have
  READ-ONLY access to Redshift -- correctly, it is a company-wide warehouse.
  Pushing 85 coordinates into a query as a literal VALUES list would work but
  would bury the one number anybody ever wants to tune (the radius) inside a
  generated string. It lives in the sites CSV instead.

SPREAD_FILTER is the crawl guard. A genuine stay is tight: after the
implied-speed fix 99.6% of intervals sit under 100 m of spread. Anything much
wider crept under the threshold in stop-start traffic and is travel, not a
visit. Rows above the limit are DROPPED and COUNTED to stderr rather than
silently skipped -- a filter nobody can see the effect of is a filter nobody
will notice has gone wrong.
"""
import csv, math, sys
from collections import Counter

EARTH_M_PER_DEG = 111_320.0
SPREAD_FILTER_M = 300


def metres(lat1, lon1, lat2, lon2):
    return math.hypot(
        (lat1 - lat2) * EARTH_M_PER_DEG,
        (lon1 - lon2) * EARTH_M_PER_DEG * math.cos(math.radians(lat1)),
    )


def load_sites(path):
    sites = []
    with open(path, encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            if not r.get("latitude"):
                continue
            sites.append((int(r["site_number"]), float(r["latitude"]),
                          float(r["longitude"]), int(r["geofence_radius_m"] or 150)))
    if not sites:
        sys.exit("no sites with coordinates -- run the G1 backfill first")
    return sites


def nearest(sites, lat, lon):
    best = None
    for n, la, lo, rad in sites:
        d = metres(lat, lon, la, lo)
        if best is None or d < best[1]:
            best = (n, d, rad)
    return best


def lit(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    sites = load_sites(sys.argv[2])

    rows, stats = [], Counter()
    with open(sys.argv[1], encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            spread = int(float(r["spread_m"] or 0))
            stats["read"] += 1
            if spread > SPREAD_FILTER_M:
                stats["dropped_spread"] += 1
                continue
            lat, lon = float(r["centroid_lat"]), float(r["centroid_lon"])
            n, d, rad = nearest(sites, lat, lon)
            within = d <= rad
            stats["at_site"] += 1 if within else 0
            rows.append({
                "device_id": r["device_id"],
                "arrived_at": r["arrived_at"],
                "departed_at": r["departed_at"],
                "dwell_minutes": float(r["dwell_minutes"]),
                "centroid_lat": lat,
                "centroid_lon": lon,
                "spread_m": spread,
                "ping_count": int(r["ping_count"] or 0),
                # Nearest site is recorded even when far away: "the nearest site
                # was 30 km off" is a useful fact, and null here would lose it.
                "matched_site_number": n,
                "distance_m": round(d),
                "within_geofence": within,
            })

    cols = ["device_id", "arrived_at", "departed_at", "dwell_minutes",
            "centroid_lat", "centroid_lon", "spread_m", "ping_count",
            "matched_site_number", "distance_m", "within_geofence"]

    print("-- generated by build_dwell.py -- do not hand-edit")
    print("begin;")
    CHUNK = 500
    for i in range(0, len(rows), CHUNK):
        print(f"insert into mt_gps_dwell ({', '.join(cols)}) values")
        print(",\n".join("(" + ", ".join(lit(r[c]) for c in cols) + ")"
                         for r in rows[i:i + CHUNK]))
        print("""on conflict (device_id, arrived_at) do update set
  departed_at = excluded.departed_at, dwell_minutes = excluded.dwell_minutes,
  centroid_lat = excluded.centroid_lat, centroid_lon = excluded.centroid_lon,
  spread_m = excluded.spread_m, ping_count = excluded.ping_count,
  matched_site_number = excluded.matched_site_number,
  distance_m = excluded.distance_m, within_geofence = excluded.within_geofence,
  built_at = now();""")
    print("commit;")

    print(f"read {stats['read']}, dropped {stats['dropped_spread']} for spread "
          f">{SPREAD_FILTER_M}m, wrote {len(rows)}, of which {stats['at_site']} "
          f"({stats['at_site']/max(len(rows),1)*100:.1f}%) inside a site geofence",
          file=sys.stderr)


if __name__ == "__main__":
    main()
