#!/usr/bin/env python3
"""
Two jobs, both part of recovering the Connecteam jobId -> Splash site crosswalk
without API access. See supabase/mt-connecteam-job-site-01.sql for why it has
to be recovered from behaviour at all.

    python build_job_site.py query sites.csv            > job_site.sql
    python build_job_site.py apply  job_site_result.csv > job_site_apply.sql

  query   Emits the READ-ONLY Redshift query. Site centres live in Supabase, so
          they are inlined here rather than hardcoded in a checked-in .sql that
          would silently go stale the day a coordinate is corrected.

  apply   Turns the query's CSV output into the Supabase upsert, grading each
          job's confidence.

WHY RESIDENCE AND NOT PING COUNT
  Geotab logs densely while moving and goes quiet while parked, so a 3-hour
  stay can be two pings while a drive-past at 5-second intervals is dozens.
  Counting pings ranks the drive-past first. Residence is the SPAN between the
  first and last ping inside a fence.
"""
import csv, sys

CREW = [
    ("b1", 2229900), ("b2", 14250258), ("b36B", 12242553), ("b36C", 3146122),
    ("b36D", 9611831), ("b36E", 2229901), ("b36F", 18805857), ("b4", 8552864),
    ("b5", 1122039), ("b6", 3324247), ("b7", 13333061), ("b8", 2217732),
    ("b9", 5855509),
]


def grade(shifts: int, modal_pct: int) -> str:
    """
    Confidence for mt_connecteam_job_site, which spells these out in full.

    NOTE THE TWO SPELLINGS, because getting them the wrong way round is a
    CHECK-constraint failure at apply time and nothing earlier:
      mt_connecteam_job_site.confidence  CONFIDENT / LIKELY / WEAK / ...
      mt_shift_site.confidence           C / L / W / F / I  (char(1))
    The refresh maps the first onto the second in SQL; this function only ever
    produces the long form.
    """
    if shifts >= 5 and modal_pct >= 80:
        return "CONFIDENT"
    if shifts >= 3 and modal_pct >= 80:
        return "LIKELY"
    if shifts >= 5 and modal_pct >= 60:
        return "WEAK"
    if shifts < 3:
        return "TOO_FEW_SHIFTS"
    return "INCONSISTENT"


def emit_query(sites_csv: str) -> None:
    rows = [r for r in csv.DictReader(open(sites_csv, encoding="utf-8")) if r.get("latitude")]
    if not rows:
        sys.exit("no sites with coordinates -- dump sites.csv from Supabase first")
    sites = " union all ".join(
        "select {sn}::int sn, {la}::float slat, {lo}::float slon, {rad}::int rad".format(
            sn=r["site_number"], la=r["latitude"], lo=r["longitude"],
            rad=r["geofence_radius_m"] or 150)
        for r in rows)
    crew = " union all ".join(
        "select '{d}'::varchar dev, {c}::bigint cid".format(d=d, c=c) if i == 0
        else "select '{d}', {c}".format(d=d, c=c)
        for i, (d, c) in enumerate(CREW))
    print(f"""-- generated by build_job_site.py -- do not hand-edit
-- READ-ONLY. SELECT only. Never writes to Redshift.
with sites as ({sites}),
crew as ({crew}),
sh as (
  select s.id shift_id,
         nullif(json_extract_path_text(s.raw_json,'jobId'),'') job_id,
         c.dev, s.start_utc, s.end_utc
  from razayya_agent_collector.connecteam_shifts s
  join crew c on c.cid = s.user_id
  where s.end_utc is not null
    and datediff(minute, s.start_utc, s.end_utc) between 5 and 1440),
ping as (
  select sh.shift_id, sh.job_id, si.sn, g.date_time
  from sh
  join razayya_agent_collector.geotab_gps g
    on g.device_id = sh.dev
   and g.date_time >= sh.start_utc and g.date_time <= sh.end_utc
  join sites si
    on abs(g.latitude - si.slat) < 0.006 and abs(g.longitude - si.slon) < 0.008
   and sqrt(power((g.latitude-si.slat)*111320,2)
          + power((g.longitude-si.slon)*111320*cos(radians(g.latitude)),2)) <= si.rad),
span as (
  select shift_id, job_id, sn,
         datediff(second, min(date_time), max(date_time))/60.0 mins
  from ping group by shift_id, job_id, sn),
best as (
  select shift_id, job_id, sn, mins from (
    select span.*, row_number() over (partition by shift_id order by mins desc, sn) rk
    from span) z where rk = 1),
tally as (select job_id, sn, count(*) shifts, sum(mins) tot from best group by job_id, sn),
modal as (
  select job_id, sn modal_site, shifts modal_shifts from (
    select tally.*, row_number() over (partition by job_id order by shifts desc, tot desc) rk
    from tally) z where rk = 1)
select m.job_id, m.modal_site, m.modal_shifts,
       t.shifts_with_a_site, t.distinct_sites,
       cast(round(100.0*m.modal_shifts/t.shifts_with_a_site) as int) modal_pct
from modal m
join (select job_id, count(*) shifts_with_a_site, count(distinct sn) distinct_sites
      from best group by job_id) t on t.job_id = m.job_id
order by t.shifts_with_a_site desc;""")


def emit_apply(result_csv: str) -> None:
    rows = list(csv.DictReader(open(result_csv, encoding="utf-8")))
    if not rows:
        sys.exit("crosswalk result is empty -- refusing to emit an upsert that would write nothing")
    print("-- generated by build_job_site.py -- do not hand-edit")
    print("begin;")
    vals = ",".join(
        "('{j}',{s},'{g}',{n},{p},{d})".format(
            j=r["job_id"], s=r["modal_site"],
            g=grade(int(r["shifts_with_a_site"]), int(r["modal_pct"])),
            n=r["shifts_with_a_site"], p=r["modal_pct"], d=r["distinct_sites"])
        for r in rows)
    print("insert into mt_connecteam_job_site "
          "(job_id,site_number,confidence,shifts_observed,modal_pct,distinct_sites) values")
    print(vals)
    print("""on conflict (job_id) do update set
  site_number = excluded.site_number, confidence = excluded.confidence,
  shifts_observed = excluded.shifts_observed, modal_pct = excluded.modal_pct,
  distinct_sites = excluded.distinct_sites, derived_at = now();""")
    print("commit;")
    conf = sum(1 for r in rows if grade(int(r["shifts_with_a_site"]), int(r["modal_pct"])) in ("CONFIDENT", "LIKELY"))
    print(f"{len(rows)} jobs, {conf} at CONFIDENT/LIKELY", file=sys.stderr)


def main() -> None:
    if len(sys.argv) < 3 or sys.argv[1] not in ("query", "apply"):
        sys.exit(__doc__)
    (emit_query if sys.argv[1] == "query" else emit_apply)(sys.argv[2])


if __name__ == "__main__":
    main()
